sudo: false
language: python
python:
  - 2.7
cache:
  directories:
    - $HOME/.cache/pip
addons:
  postgresql: "9.3"
  apt:
    packages:
    - libhdf5-serial-dev
    - default-jre
services:
  - redis-server
env: PIP_DOWNLOAD_CACHE=$HOME/.cache/pip
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=2.7
  - conda install --yes -n condaenv pip
  - source activate condaenv
install:
 - conda install --yes -c https://conda.binstar.org/ska pycairo
 - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy
 - conda install --yes -c dan_blanchard python-coveralls
 - pip install --upgrade pip setuptools
 - pip install cython
 - pip install git+https://github.com/gallantlab/pycortex.git --egg
 - cat requirements.txt | xargs -n 1 -L 1 -I{} pip install '{}'
 - wget -O /tmp/toolbox-0.6.1-release.zip http://search.maven.org/remotecontent?filepath=org/openprovenance/prov/toolbox/0.6.1/toolbox-0.6.1-release.zip
before_script:
  - psql -c "CREATE USER neurovault WITH PASSWORD 'neurovault';" -U postgres
  - psql -c "ALTER USER neurovault CREATEDB;" -U postgres
  - ./manage.py collectstatic --noinput
script: coverage run manage.py test
