db:
  image: postgres

data:
  image: cogniteev/echo
  volumes:
    - /var/www/image_data

uwsgi:
  restart: always
  image: neurovault/neurovault
  volumes_from:
    - data
  volumes:
    - .:/code
    - /var/www/static
  links:
    - db
    - redis
    - data

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
  volumes:
    - nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
    - data
  links:
    - uwsgi
    - data

redis:
  restart: always
  image: redis

worker:
  image: neurovault/neurovault
  command: celery worker -A neurovault.celery -Q default -n default@%h
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
    - data
  links:
    - db
    - redis
    - data
